LICENSE.txt
cloudpassage/server.py
tests/integration/test_integration_server.py

Adding license file
CS-8 added issues endpoint to server.py
Update test_integration_server.py
CS-8 update agent_firewall_logs to have pagination

CS-8 Add /v1/servers/:id/issues and /v1/servers/:id/firewall_logs

---

.gitchangelog.rc
CHANGELOG.md
CHANGELOG.rst
cloudpassage/server.py

Merge develop into master

---

cloudpassage/halo.py
tests/integration/test_integration_alert_profile.py
tests/integration/test_integration_configuration_policy.py
tests/integration/test_integration_event.py
tests/integration/test_integration_fim_policy.py
tests/integration/test_integration_firewall_policy.py
tests/integration/test_integration_halo.py
tests/integration/test_integration_http_helper.py
tests/integration/test_integration_lids_policy.py
tests/integration/test_integration_scan.py
tests/integration/test_integration_server.py
tests/integration/test_integration_server_group.py
tests/integration/test_integration_special_events_policy.py
tests/integration/test_integration_system_announcement.py
tests/unit/test_unit_halo.py

Bring Useragent string into compliance with RFC 2616

Formatting user agent more like RFC 2616 says we should

---

cloudpassage/__init__.py
cloudpassage/http_helper.py
cloudpassage/retry.py
cloudpassage/utility.py
tests/unit/test_unit_utility.py

Add delayed retry to http helper

CS-259 delayed retry 

---

cloudpassage/__init__.py
cloudpassage/issue.py
tests/integration/test_integration_issue.py
tests/unit/test_unit_issue.py

added list_all, describe, and resolve methods

CS-269 add issues endpoint to the SDK

---

cloudpassage/__init__.py
cloudpassage/local_user_group.py
tests/integration/test_integration_server.py
tests/unit/test_unit_local_user_group.py

Added LocalUserGroup to __init__.py

---

CHANGELOG.rst
cloudpassage/__init__.py

merge from develop to master

---

.codeclimate.yml

chg: test: Updating .codeclimate.yml !minor

---

cloudpassage/exceptions.py

chg: dev: Re-factor exceptions, remove duplicate code. !refactor

---

cloudpassage/event.py

Add webhook for auto-building docs
Closes #129

chg: doc: Fixing broken link in Event() documentation. !minor

---

cloudpassage/agent_upgrade.py
cloudpassage/alert_profile.py
cloudpassage/api_key_manager.py
cloudpassage/configuration_policy.py
cloudpassage/cve_exception.py
cloudpassage/event.py
cloudpassage/fim_policy.py
cloudpassage/firewall_policy.py
cloudpassage/halo.py
cloudpassage/http_helper.py
cloudpassage/issue.py
cloudpassage/local_user_group.py
cloudpassage/sanity.py
cloudpassage/scan.py
cloudpassage/server.py
cloudpassage/server_group.py
cloudpassage/special_events_policy.py
cloudpassage/system_announcement.py
cloudpassage/time_series.py
cloudpassage/utility.py

chg: doc: Documentation improvements. !minor

---

.travis.yml
requirements-testing.txt
run_tests.sh
tests/integration/test_integration_configuration_policy.py
tests/integration/test_integration_firewall_policy.py

chg: test: Refactor for testing speed. !minor

---

cloudpassage/http_helper.py
cloudpassage/utility.py
requirements-testing.txt
tests/integration/test_integration_http_helper.py
tests/unit/test_unit_utility.py

Re-pinned pytest and associated testing requirements.
Closes #159

chg: dev: Improved docs and tests for param sanitization.

---

cloudpassage/scan.py
cloudpassage/server.py

chg: doc: Improve documentation for server and scan objects. !minor

---

docs/source/server.rst

chg: doc: Fix docs for Server.list_packages(). !minor

---

cloudpassage/time_series.py
docs/source/time_series.rst

chg: doc: Cleaned up TimeSeries() docs. !minor

---

cloudpassage/event.py
tests/integration/test_integration_event.py

new: usr: Create stream() generator method in Event class.

---

cloudpassage/api_key_manager.py

chg: usr: Using safer yaml.SafeLoader in ApiKeyManager.

---

cloudpassage/agent_upgrade.py
cloudpassage/alert_profile.py
cloudpassage/configuration_policy.py
cloudpassage/cve_details.py
cloudpassage/cve_exception.py
cloudpassage/event.py
cloudpassage/fim_policy.py
cloudpassage/firewall_policy.py
cloudpassage/halo_endpoint.py
cloudpassage/issue.py
cloudpassage/lids_policy.py
cloudpassage/local_user_account.py
cloudpassage/local_user_group.py
cloudpassage/scan.py
cloudpassage/server.py
cloudpassage/server_group.py
cloudpassage/special_events_policy.py
cloudpassage/system_announcement.py
tests/integration/test_integration_alert_profile.py
tests/unit/test_unit_system_announcement.py

new: usr: API version selectors for abstractions.

---

cloudpassage/sanity.py
tests/unit/test_unit_sanity.py

fix: usr: Fixed validation failures on v3 issues ID format.
